name: insights-user
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - adal==1.2.7
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - azure-batch==14.2.0
      - azure-common==1.1.28
      - azure-core==1.34.0
      - azure-identity==1.23.0
      - azure-keyvault-secrets==4.9.0
      - azure-mgmt-batch==18.0.0
      - azure-mgmt-core==1.5.0
      - azure-mgmt-datafactory==9.2.0
      - azure-storage-blob==12.27.0
      - build==1.3.0
      - cachetools==5.5.2
      - cattrs==25.3.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cryptography==45.0.3
      - cycler==0.12.1
      - db-dtypes==1.4.3
      - distro==1.9.0
      - et-xmlfile==2.0.0
      - filelock==3.19.1
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - future==1.0.0
      - google-analytics-data==0.18.18
      - google-api-core==2.24.2
      - google-api-python-client==2.169.0
      - google-auth==2.40.1
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.2
      - google-cloud-bigquery==3.33.0
      - google-cloud-core==2.4.3
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpcio==1.72.0rc1
      - grpcio-status==1.72.0rc1
      - h11==0.16.0
      - hdbscan==0.8.40
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - hyperopt==0.2.7
      - idna==3.10
      - iniconfig==2.1.0
      - isodate==0.7.2
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - lightgbm==4.6.0
      - llvmlite==0.45.1
      - looker-sdk==25.16.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - meraki==2.0.3
      - msal==1.32.3
      - msal-extensions==1.3.1
      - msrest==0.7.1
      - msrestazure==0.6.4.post1
      - multidict==6.6.4
      - networkx==3.5
      - numba==0.62.1
      - numpy==2.2.6
      - oauthlib==3.2.2
      - openai==2.6.0
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.2.3
      - pandas-gbq==0.29.0
      - patsy==1.0.1
      - pillow==11.2.1
      - pluggy==1.6.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==6.31.0
      - psycopg2==2.9.11
      - py4j==0.10.9.9
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-settings==2.11.0
      - pydata-google-auth==1.9.1
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pymssql==2.3.4
      - pynndescent==0.5.13
      - pyodbc==5.2.0
      - pyparsing==3.2.3
      - pyproject-hooks==1.2.0
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.7.1
      - scipy==1.16.0
      - seaborn==0.13.2
      - six==1.17.0
      - sniffio==1.3.1
      - statsmodels==0.14.5
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - uritemplate==4.1.1
      - urllib3==2.4.0
      - yarl==1.20.1
